class Optimization:

    @classmethod
    def pre_optimization(cls, alerts, level: int, max_procs: int): ...
    @classmethod
    def optimization(cls, spread_graphs: list, level: int, max_procs: int, alerts: dict, events: list): ...
    @classmethod
    def post_optimization(cls, ukc, level: int, max_procs: int): ...
