class Integration:
    elastic = None
    config: dict
    max_procs: int
    zones: dict
    cache: str
    apt_preconditions: dict
    apt_postconditions: dict

    def __init__(self, argv, config_path: str = "config_standard.json"):
        self.event = bool
        self.event_cache = str()
        ...
    def integrate(self) -> None: ...

    def get_events(self) -> list: ...

    @staticmethod
    def parse_config(config_path: str) -> dict: ...
    @staticmethod
    def normalize_alert(alert: dict) -> dict: ...
    def get_alerts(self, earliest_date: str, latest_date: str, date_format: str, cache: str) -> list: ...
    def get_alert_details(self, ma) -> tuple[str, str]: ...
    def output(self, data): ...
